name: Build Coreboot for a Chromebook, with custom logo
run-name: Build ${{ github.event.issue.title }} for ${{ github.actor }}
on:
  issues:
    types: 
      - opened
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Install Dependencies
        run: npm install
        working-directory: action
      - name: Run Script
        run: npm start
        working-directory: action
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}