name: Build Coreboot for a Chromebook, with custom logo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issues:
    types: 
      - opened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  